---
- name: apply v4 rules
  include_tasks: apply_rules.yml
  vars:
    ip_version: ""

- name: apply v6 rules
  include_tasks: apply_rules.yml
  vars:
    ip_version: "6"

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: "'fail2ban.service' in ansible_facts.services"

- name: restart lxd
  service:
    name: lxd
    state: restarted
  when: "'lxd.service' in ansible_facts.services"

- name: restart docker
  service:
    name: docker
    state: restarted
  when: "'docker.service' in ansible_facts.services"
